### ISSUE TITLE
Button swap?

### ISSUE THREAD

**Issue by liquidcross** [JohnnyonFlame/EverSDK#2]
Is there anyway to reconfigure the buttons? Running Evercade fw3.0.0 (patched via EverPatcher 5.0.0), and the latest version of PICO-8 (8_0.2.5.g).

**Comment by JohnnyonFlame** [comment]
Specific fixes for the Evercade Handheld are coming along - when the update drops, problems with the handheld mapping will be fixed. If you _need_ to do this right now, you can always just force `SDL_GAMECONTROLLERCONFIG`.

The update will fix the missing `guide` button and bring better defaults, stay tuned.
